# Site settings
title: "Aethermoor: Industrial Fantasy RPG"
description: "A tabletop RPG where magic meets the industrial revolution"
baseurl: "/aethermoor-rpg" # Replace with your repo name
url: "https://[YOUR-USERNAME].github.io" # Replace with your username

# Build settings
theme: jekyll-theme-cayman
# Alternative themes: minima, jekyll-theme-minimal, jekyll-theme-slate

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Player's Guide"
    url: "/players-guide/"
  - title: "Rules"
    url: "/rules/"
  - title: "Setting"
    url: "/setting/"
  - title: "GM Guide"
    url: "/gm-guide/"
  - title: "Downloads"
    url: "/downloads"

# Markdown settings
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..3
